# Generated by Django 6.0.3 on 2026-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('priority', models.CharField(choices=[('H', 'Yüksek (Acil)'), ('M', 'Orta'), ('L', 'Düşük')], default='M', max_length=1, verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completed', '-created_at'],
            },
        ),
    ]
